-- SELECT DISTINCT ORDER_DATE, USER_ID
-- FROM USERORDERSPRODUCT;


SELECT 
                ORDER_GROUP.ORDER_TIMESTAMP, 
                ORDER_GROUP.USER_ID, 
                ORDER_GROUP.ORDER_DETAILS, 
                ORDER_GROUP.DELIVERY_STATUS
            FROM (
                SELECT 
                    ORDER_TIMESTAMP, 
                    USER_ID, 
                    LISTAGG(PRO_ID, ', ') WITHIN GROUP (ORDER BY PRO_ID) AS ORDER_DETAILS, 
                    DELIVERY_STATUS
                FROM USERORDERSPRODUCT
                WHERE USER_ID = :userId
                GROUP BY ORDER_TIMESTAMP, USER_ID, DELIVERY_STATUS
                ORDER BY ORDER_TIMESTAMP DESC
            ) ORDER_GROUP



-- INSERT INTO USERORDERSPRODUCT (USER_ID, PRO_ID, DELIVERY_STATUS, ORDER_DATE)
-- VALUES (1235, 3, 'PENDING', TO_TIMESTAMP('30-AUG-24 12.00.00.000000000 AM', 'DD-MON-YY HH12.MI.SS.FF AM'));