-- INSERT INTO PRODUCTS(
--     PRO_ID,
--     NAME,
--     DESCRIPTION,
--     IMAGE,
--     PRICE,
--     QUANTITY
-- ) VALUES (
--     6,
--     'Product6',
--     'this is a really good product',
--     'https://www.anime-planet.com/images/studios/banners/ufotable-29.jpg',
--     500,
--     50
-- );

-- INSERT INTO MERCHPRODUCEPROD ( PRO_ID, MER_ID) VALUES ( 1, 1234 );
-- INSERT INTO MERCHPRODUCEPROD ( PRO_ID, MER_ID) VALUES ( 2, 1234 );
-- INSERT INTO MERCHPRODUCEPROD ( PRO_ID, MER_ID) VALUES ( 3, 1234 );
-- INSERT INTO MERCHPRODUCEPROD ( PRO_ID, MER_ID) VALUES ( 4, 1234 );
-- INSERT INTO MERCHPRODUCEPROD ( PRO_ID, MER_ID) VALUES ( 5, 1234 );

-- TRUNCATE TABLE USERORDERSPRODUCT;

-- INSERT INTO USERS (USER_ID, USER_NAME, NAME, DOB, EMAIL, CITY, STREET, HOUSE, PHONE) 
--             VALUES (2234, 'Siifu1', 'Sifat Bin Asad', TO_DATE('01/01/1999', 'MM/DD/YYYY'), 'meow@gmail.com', 'Dhaka', 'Dhanmondi', '12', '01700000000');

-- INSERT INTO LOGIN (LOGIN_ID, PASSWORD, ROLE, ID)
--             VALUES (2234, '1234', 'USER', 2234);


-- INSERT INTO MERCHANDISER (MER_ID,USER_NAME, NAME, DESCRIPTION, EMAIL, CITY, STREET, HOUSE, PHONE)
--             VALUES (2234, 'sfmerch1', 'SIFAT', 'We sell merch', 'chikachika@gmail.com', 'Dhaka', 'Dhanmondi', '12', '01700000000');

-- INSERT INTO LOGIN (LOGIN_ID, PASSWORD, ROLE, ID)
--             VALUES (2235, '1234', 'MERCHANDISER', 2234);
-- INSERT INTO MERCHPRODUCEPROD ( PRO_ID, MER_ID) VALUES ( 6, 2234 );

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) VALUES (1, 3);
INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) VALUES (2, 3);
INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) VALUES (3, 3);
INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) VALUES (4, 3);
INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) VALUES (5, 3);


