
INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (3, 1);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (4, 1);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (5, 1);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (6, 2);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (6, 3);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (7, 4);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (8, 1);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (9, 3);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (9, 4);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (9, 5);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (10, 3);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (10, 4);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (41, 6);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (44, 7);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (45, 8);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (46, 9);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (47, 3);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (47, 10);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (49, 11);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (51, 11);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (51, 2);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (51, 12);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (55, 7);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (56, 7);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (57, 13);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (59, 11);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (59, 14);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (59, 15);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (61, 16);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (62, 17);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (64, 11);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (65, 18);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (65, 4);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (65, 3);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (65, 19);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (65, 20);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (65, 21);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (66, 22);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (67, 23);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (69, 24);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (70, 25);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (72, 2);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (12, 3);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (12, 4);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (13, 27);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (14, 2);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (15, 1);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (16, 2);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (17, 4);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (17, 28);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (18, 29);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (18, 20);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (19, 30);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (20, 4);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (20, 2);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (20, 31);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (21, 7);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (22, 1);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (23, 7);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (24, 3);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (24, 4);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (24, 20);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (25, 3);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (26, 17);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (27, 17);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (76, 32);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (77, 33);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (77, 34);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (28, 35);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (78, 36);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (29, 37);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (80, 38);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (80, 39);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (30, 40);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (81, 41);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (82, 42);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (31, 43);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (58, 44);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (84, 45);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (32, 46);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (85, 47);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (33, 35);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (86, 48);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (87, 33);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (34, 49);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (88, 7);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (89, 50);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (89, 51);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (35, 37);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (90, 4);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (36, 46);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (91, 32);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (92, 7);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (93, 47);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (37, 52);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (94, 53);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (95, 54);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (38, 55);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (96, 56);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (39, 57);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (39, 58);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (40, 59);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (200, 60);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (200, 61);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (201, 62);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (202, 63);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (203, 59);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (204, 18);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (205, 64);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (206, 7);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (207, 7);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (208, 65);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (209, 7);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (211, 66);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (212, 67);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (213, 68);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (214, 69);

INSERT INTO COMPANYHASMEDIA (MEDIA_ID, COM_ID) 
VALUES (215, 7);
--------------------------------------------------------------------------------------------------------------------------------, 0, 0
-- MERCHPRODUCEPROD
-------------------------------------------------------------------------------------------------------------------------------, 0, 0-

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (100, 1235);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (101, 1235);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (102, 1235);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (103, 1235);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (104, 1235);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (105, 1235);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (106, 1235);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (107, 1235);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (108, 1235);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (109, 1235);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (110, 1236);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (111, 1236);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (112, 1236);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (113, 1236);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (114, 1236);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (115, 1236);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (116, 1236);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (117, 1236);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (118, 1236);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (119, 1236);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (120, 1237);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (121, 1237);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (122, 1237);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (123, 1237);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (124, 1237);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (125, 1237);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (126, 1237);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (127, 1237);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (128, 1237);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (129, 1237);

INSERT INTO MERCHPRODUCEPROD (PRO_ID, MER_ID) 
VALUES (130, 1235);
--------------------------------------------------------------------------------------------------------------------------------, 0, 0
--PRODUCTBASEDONMEDIA
-------------------------------------------------------------------------------------------------------------------------------, 0, 0-
INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (100, 6);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (101, 6);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (102, 7);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (103, 7);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (104, 46);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (105, 46);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (106, 67);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (109, 16);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (110, 16);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (111, 17);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (112, 17);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (113, 18);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (114, 18);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (115, 19);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (116, 19);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (117, 76);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (118, 77);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (119, 77);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (120, 78);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (121, 78);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (122, 79);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (123, 79);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (124, 29);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (125, 29);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (126, 80);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (127, 80);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (128, 81);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (129, 81);

INSERT INTO PRODUCTBASEDONMEDIA (PRO_ID, MEDIA_ID) 
VALUES (130, 82);



INSERT INTO COLLABORATE (PRO_ID, COM_ID, MER_ID, DESCRIPTION, C_STATUS)
SELECT 
    p.PRO_ID, 
    c.COM_ID, 
    m.MER_ID,
    'Accepted collaboration',  -- Description
    'ACCEPTED'                 -- Status
FROM 
    PRODUCTBASEDONMEDIA p
JOIN 
    COMPANYHASMEDIA c ON p.MEDIA_ID = c.MEDIA_ID
JOIN 
    MERCHPRODUCEPROD m ON p.PRO_ID = m.PRO_ID
WHERE 
    c.COM_ID IS NOT NULL 
AND 
    m.MER_ID IS NOT NULL;