START dropAll.sql;
START abstract.sql;
START data.sql;
START views.sql;
START triggers.sql;
START procedures.sql;
START insert.sql;


SELECT 
    M.MEDIA_ID, 
    M.TITLE
FROM 
    MEDIA M
JOIN 
    PREFERREDGENRE P ON REGEXP_LIKE(M.GENRE, REPLACE(P.GENRES, ',', '|'))
WHERE 
    P.USER_ID = 1234
    AND NOT EXISTS (
        SELECT 1 
        FROM USERWATCHANDFAVORITE UWF 
        WHERE UWF.USER_ID = P.USER_ID 
        AND UWF.MEDIA_ID = M.MEDIA_ID
    )
ORDER BY 
    M.RATING DESC;


    SELECT DISCUSSION.DIS_ID, TITLE, TOPIC, DISCUSSION.DESCRIPTION, REPLY_COUNT , DISCUSSIONABOUTMEDIA.DIS_DATE ,MEDIA.POSTER
                FROM DISCUSSION JOIN DISCUSSIONABOUTMEDIA 
                    ON DISCUSSION.DIS_ID = DISCUSSIONABOUTMEDIA.DIS_ID 
                JOIN MEDIA 
                    ON DISCUSSIONABOUTMEDIA.MEDIA_ID = MEDIA.MEDIA_ID
                    WHERE PARENT_TOPIC IS NULL
                ORDER BY DISCUSSIONABOUTMEDIA.DIS_DATE DESC, DISCUSSION.REPLY_COUNT DESC;