START dropAll.sql;
START abstract.sql;
START data.sql;
START views.sql;
START triggers.sql;
START procedures.sql;
START insert.sql;


SELECT 
    M.MEDIA_ID, 
    M.TITLE
FROM 
    MEDIA M
JOIN 
    PREFERREDGENRE P ON REGEXP_LIKE(M.GENRE, REPLACE(P.GENRES, ',', '|'))
WHERE 
    P.USER_ID = 1234
    AND NOT EXISTS (
        SELECT 1 
        FROM USERWATCHANDFAVORITE UWF 
        WHERE UWF.USER_ID = P.USER_ID 
        AND UWF.MEDIA_ID = M.MEDIA_ID
    )
ORDER BY 
    M.RATING DESC;


    SELECT DISTINCT DISCUSSION.DIS_ID, TITLE, TOPIC, DISCUSSION.DESCRIPTION, REPLY_COUNT, 
                DISCUSSIONABOUTMEDIA.DIS_DATE, MEDIA.POSTER
FROM DISCUSSION 
JOIN DISCUSSIONABOUTMEDIA 
    ON DISCUSSION.DIS_ID = DISCUSSIONABOUTMEDIA.DIS_ID 
JOIN MEDIA 
    ON DISCUSSIONABOUTMEDIA.MEDIA_ID = MEDIA.MEDIA_ID
WHERE PARENT_TOPIC IS NULL
ORDER BY DISCUSSIONABOUTMEDIA.DIS_DATE DESC, DISCUSSION.REPLY_COUNT DESC;


SELECT 
    C.COM_ID, C.USER_NAME, C."NAME", C.IMG, C.DESCRIPTION, C.EMAIL, 
    COUNT(CHM.MEDIA_ID) AS MEDIA_COUNT
FROM 
    COMPANY C
JOIN 
    COMPANYHASMEDIA CHM ON C.COM_ID = CHM.COM_ID
GROUP BY 
    C.COM_ID, C.USER_NAME, C."NAME", C.IMG, C.DESCRIPTION, C.EMAIL
ORDER BY 
    MEDIA_COUNT DESC;

SELECT * from MERCHPRODUCEPROD;


SELECT P.PRO_ID, P.NAME, P.DESCRIPTION, P.IMAGE, P.PRICE, P.QUANTITY
                FROM PRODUCTS P
                JOIN PRODUCTBASEDONMEDIA PB ON P.PRO_ID = PB.PRO_ID
                JOIN COLLABORATE COL ON P.PRO_ID = COL.PRO_ID
                WHERE COL.COM_ID = 7
                AND COL.C_STATUS = 'ACCEPTED'
                AND P.QUANTITY > 0;