CREATE OR REPLACE TRIGGER update_product_quantity
AFTER INSERT OR UPDATE ON USERORDERSPRODUCT
FOR EACH ROW
WHEN (NEW.DELIVERY_STATUS = 'PENDING')
BEGIN
    UPDATE PRODUCTS
    SET QUANTITY = QUANTITY - :NEW.ORDER_QUANTITY
    WHERE PRO_ID = :NEW.PRO_ID;
END;
/

CREATE OR REPLACE TRIGGER increase_product_quantity
BEFORE DELETE ON USERORDERSPRODUCT
FOR EACH ROW
WHEN (OLD.DELIVERY_STATUS = 'PENDING')
BEGIN
    UPDATE PRODUCTS
    SET QUANTITY = QUANTITY + :OLD.ORDER_QUANTITY
    WHERE PRO_ID = :OLD.PRO_ID;
END;
/

CREATE OR REPLACE TRIGGER calculate_age
BEFORE INSERT OR UPDATE ON USERS
FOR EACH ROW
BEGIN
    :NEW.AGE := FLOOR(MONTHS_BETWEEN(SYSDATE, :NEW.DOB) / 12);
END;
/
